#!/bin/bash

# This sample demonstrates how to install a package (libpng)
# from a project's CMakeLists.txt
# Libpng depends on zlib which will be installed automatically. The dependency information
# is stored in the cake-depends-db.cmake file in the root of the Cake repository.

set -ex

# path for cakepkg and cake commands
export PATH=${PWD}/../..:$PATH

# the path to the cake config file. Will be used by cakepkg (and cake)
# to construct the cmake command lines
export CAKE_CONFIG_FILE=${PWD}/cakecfg.cmake

# the CMakeLists.txt calls cake_find_package(PNG) and reports the result
cmake -H. -B_build/03_cmakelists_libpng -DCMAKE_PREFIX_PATH=$PWD/_install



