#!/bin/bash

# This is the same script as ./run except
# it uses the convenience shell command 'cake' to call and pass parameters
# to the 'cmake' command

# This sample is almost the same as 05_subproj_cake_depends.
# The difference is that in this case subprojlib does not have a cake-depends.cmake
# file in its root to describe the dependency information.
# Instead, it just uses a conditional cake_find_package(ZLIB ...)
# command in its CMakeLists.txt (see there: https://github.com/tamaskenez/cake-sample-subprojlib-cake-find-package)

set -ex

# path for cakepkg and cake commands
export PATH=${PWD}/../..:$PATH

# the path to the cake config file. Will be used by cakepkg (and cake)
# to construct the cmake command lines
export CAKE_CONFIG_FILE=${PWD}/cakecfg.cmake

# calls cmake for the current directory as source
# uses cmake command line created from cakecfg.cmake
# Play with the following build settings. You can execute
# ./clear remove previous build and install files before changing
# the build settings.
#
# - SUBPROJLIB_WITH_ZLIB controls to build subprojlib with or without zlib.
# - SUBPROJLIB_AS_SUBDIRECTORY controls to include subprojlib as a subproject (in a subdirectory)
#   or as an external project, built in configuration-time
# - SUBPROJLIB_WITH_CAKE_FIND_PACKAGE controls the way subprojlib publishes its dependency information (zlib).
#   There are two ways to do this. They're demonstrated on the 'master' and the 'master_cfp' branches
#   of the subprojlib repository. So this option controls which branch to check out:
#   1. if SUBPROJLIB_WITH_CAKE_FIND_PACKAGE=0 then the master project will check out the 'master' branch of
#      the subprojlib repository. On this branch, subprojlib's CMakeLists.txt uses plain find_package()
#      commands. It also contains a cake-depends.cmake script which installs zlib if needed
#   2. if SUBPROJLIB_WITH_CAKE_FIND_PACKAGE=1 then the 'master_cfp' branch will be checked out. On this
#      branch there's no cake-depends.cmake file. Instead, the subprojlib's CMakeLists.txt uses
#      cake_find_package(ZLIB REQUIRED URL ...) to install zlib.
cake . -DSUBPROJLIB_WITH_ZLIB=0 -DSUBPROJLIB_AS_SUBDIRECTORY=0 -n

./_install/bin/sample05




