set(_cake_message_keywords STATUS WARNING AUTHOR_WARNING SEND_ERROR FATAL_ERROR DEPRECATION)

function(cake_message2 _cm_first _cm_second)
	message("${_cm_first}" "[cake] ${_cm_second}" ${ARGN})
endfunction()

function(cake_message _cm_first)
	list(FIND _cake_message_keywords "${_cm_first}" idx)
	if(idx EQUAL -1)
		message("[cake] ${_cm_first}" ${ARGN})
	else()
		cake_message2("${_cm_first}" ${ARGN})
	endif()
endfunction()

function(list_to_command_line_like_string var_out)
	unset(s)
	foreach(i ${ARGN})
		if(DEFINED s)
			set(s "${s} ")
		endif()
		string(REPLACE ";" "\;" i "${i}")
		string(FIND "${i}" " " idx)
		if(idx EQUAL -1)
			set(s "${s}${i}")
		else()
			set(s "${s}\"${i}\"")
		endif()
	endforeach()
	set(${var_out} "${s}" PARENT_SCOPE)
endfunction()